### ISSUE TITLE
Update timezone

### ISSUE THREAD

**Issue by kalkins** [Kodeworks/liquidator-backend#14]

**Comment by Yogendra0Sharma** [comment]
@kalkins What timezone we have to use.
current timezone is UTC

`TIME_ZONE = 'UTC'`

**Comment by FredrikAugust** [comment]
I believe `UTC+2` is the correct timezone for Norway.

**Comment by FredrikAugust** [comment]
Or `GMT+2`

**Comment by kalkins** [comment]
Accidentally fixed in #18

**Comment by FredrikAugust** [comment]
What do you think about this change @Yogendra0Sharma? Seems good?
