### ISSUE TITLE
Standardize error messages

### ISSUE THREAD

**Issue by kalkins** [Kodeworks/liquidator-backend#33]
The error messages returned from Django rest framework, simplejwt and django itself are not on the same format. The rest framework uses the `detail` key, while django seems to use `error`. The rest framework and simplejwt also uses the `code` key sometimes. When `create` and `update` views are missing fields, or there is an error for a field, the field name is used as key, not `error` or `detail`.

This should be standardized and coordinated with the frontend team to make it easier to display the errors to the user.

**Comment by FredrikAugust** [comment]
Absolutely. As of now there is some inconsistency with the Swagger API (rest framework), and Django (at least that's how I think it works). This makes it very hard for us to display errors, as we don't know what key the error will be on.

**Comment by nicomni** [comment]
> Absolutely. As of now there is some inconsistency with the Swagger API (rest framework), and Django (at least that's how I think it works). This makes it very hard for us to display errors, as we don't know what key the error will be on.

I agree

**Comment by kalkins** [comment]
@FredrikAugust  @NicolajNiels1 @KaizerTilt 
I propose using this format:
```
{
    'error_type': ERROR_TYPE,
    'errors': [],
    'field_errors': {}
}
```

Here ERROR_TYPE is an enum with values 'form_error', 'jwt_error', and 'error'.
`errors` is a list of errors that aren't tied to specific fields.
`field_errors` is an object with the field name as keys and a list of errors as the values. This is only used when the type is form error.
