### ISSUE TITLE
Make the getCompanyByID endpoint return the users role in the companyy

### ISSUE THREAD

**Issue by FredrikAugust** [Kodeworks/liquidator-backend#44]
As of now, I can't see any way to figure out what the role of the user is, so in the frontend I'm simply assuming the user is the owner of every company, and rather be rejected by the backend if the permissions are not sufficient to perform a certain action.

**Comment by FredrikAugust** [comment]
And make it return the other users also in the company, so that we can show it and manipulate it on the frontend.

**Comment by nicomni** [comment]
Topic for discussion in next review meeting! 🧐

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FredrikAugust** [comment]
Yes, but it would be nice if this could have been addressed before Friday,
as there is currently no way to get the roles of a user.
