### ISSUE TITLE
Can't update company even though I created it 

### ISSUE THREAD

**Issue by FredrikAugust** [Kodeworks/liquidator-backend#51]
I'm trying to test the frontend interaction with the backend, and I ran into a bug. 

I create a company by using `POST /company/`, but when I try to update the company with `PUT /company`, I simply get a 403 with the message

> You don't have access to do this operation on this company

I don't see any reason why it should be like this, when I'm the owner of the company.

**Comment by FredrikAugust** [comment]
Wireshark dump of exchange.

```
PUT /company/ HTTP/1.1
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTYzNzIxOTg2LCJqdGkiOiIwY2FlNWZhYTY0Yjc0MTk0OTM2MGZmM2Q2MGNkNDYyYiIsInVzZXJfaWQiOjcyM30.t06F7k9IEwiwqGoy7Ye9bw__T_vssFQ0Md9bzaQk_lE
content-type: application/json
Referer: http://localhost/
User-Agent: Mozilla/5.0 (linux) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0
Accept-Language: en
Accept: */*
Origin: http://localhost
host: localhost:8000
accept-encoding: gzip, deflate
content-length: 52
Connection: close

{"id":54,"name":"Test company v2","org_nr":"108088"}

HTTP/1.1 403 Forbidden
Date: Sun, 21 Jul 2019 14:58:06 GMT
Server: WSGIServer/0.2 CPython/3.7.4
Content-Type: application/json
Vary: Accept, Origin
Allow: GET, POST, PUT, DELETE, HEAD, OPTIONS
X-Frame-Options: SAMEORIGIN
Content-Length: 71
Access-Control-Allow-Origin: http://localhost

{"detail":"You don't have access to do this operation on this company"}
```

**Comment by FredrikAugust** [comment]
This appears to apply to deletion as well, ie. `DELETE /company/`.

**Comment by FredrikAugust** [comment]
I think I'm just bad at programming cause it works now.

**Comment by FredrikAugust** [comment]
Okay, so after quite some time trying to figure out the nature of this I finally figured it out.

In the swagger API docs, you have defined the query body to `PUT /company/` as following:

```json
{
  "id": 0,
  "name": "string",
  "org_nr": "string"
}
```

Which I tried to use when testing my application. Now, this is where I ran into the problem of getting `403` (forbidden). You see, when you submit a valid request in this format, you will get a `403` no matter what with the message

> You don't have access to do this operation on this company

So, naturally, I thought there was a problem with the permission system, as that is what I'm being told. It turned out however, that the problem is that the request should **not** be structured as defined in swagger, but `id` should be replaced with `company_id`. This took me longer than I would like to admit to figure out, and I ended up having to browse the code base of the back end to figure out the issue.

This really does highlight the importance of well-maintained documentation, and I hope you could double check the swagger API when you have some spare time to make sure issues like this are avoided.

I will leave the issue open so that the others on the team can read through it if they want.

**Comment by kalkins** [comment]
The thing is that every request, except login and such, requires a `company_id`, so the backend knows which company is being edited, and can check permissions. For most `POST` and `PUT`s this is natural, as they have a `company_id` field in the object. For `GET` and `DELETE` I have specified that a `company_id` field is required.

However, when handling a company it doesn't make sense to send both `id` and `company_id`. It seems like I made it so that `company_id` was used for both, and implemented that it the backend and API. Then I forgot, and thought I had done it the other way around (which I now think is more natural), so when I updated the API a few days ago I didn't think to add `company_id` to that object.

I am sorry about the confusion, and I'll fix this right away. But there's two ways to fix this: Either I can just fix the documentation, or I can change the implementation so that it uses `id` instead of `company_id`. What do you think?

**Comment by FredrikAugust** [comment]
Fixing the documentation is good, thanks :)

**Comment by nicomni** [comment]
Great discussion!
I have one comment, and I think I've mentioned it before.
Regarding this:
> This really does highlight the importance of well-maintained documentation, and I hope you could double check the swagger API when you have some spare time to make sure issues like this are avoided.

I think it puts a lot of dependency and pressure on @kalkins, being that he's the only one able to edit the Swagger API. To mediate this we should consider using the GitHub wiki or something that's editable by all of us. Any thoughts?

**Comment by FredrikAugust** [comment]
Frankly, whatever works for the backend team works for me. I will happily go the extra mile to navigate some pre-Win95-pre-netscape (yes this is a stab at [doxygen](http://www.doxygen.nl/)) website if that means that the documentation is up-to-date.

The ideal solution would of course be to have an API spec auto-generated by Django, but from what I gathered that seemed to be quite some work.

So to answer your question;
Yes, I believe Github Wiki will work well, as that allows us (the frontend) to go in and correct mistakes etc. are they to occur.

**Comment by kalkins** [comment]
Related: #55

**Comment by FredrikAugust** [comment]
Fixed with the introduction of auto-swag.

**Comment by nicomni** [comment]
> Fixed with the introduction of auto-swag.

Auto-swag 😎 	👍
