### ISSUE TITLE
Mismatch between test and swagger

### ISSUE THREAD

**Issue by FredrikAugust** [Kodeworks/liquidator-backend#53]
https://github.com/Kodeworks/liquidator-backend/blob/708c07884278f089ac47f13352ed5243118803f0/custom_auth/tests.py#L71

No password in test, but password is in swagger.

https://app.swaggerhub.com/apis/kw-liquidator/Liquidator/1.0.0#/user/updateUser

**Comment by kalkins** [comment]
@FredrikAugust This is partly a documentation issue and partly a backend bug. There is a pull request out that lets the password be an optional field. I'll update the API to reflect that too

**Comment by kalkins** [comment]
Unfortunately, while I've fixed the swagger object, the endpoint example doesn't reflect that `password` is optional. Maybe we could add a custom example that makes this clear?
