### ISSUE TITLE
Consider use of auto-generated API spec/documentation from backend

### ISSUE THREAD

**Issue by henriean** [Kodeworks/liquidator-backend#55]
Enforcing consistency between swagger and backend has proved a bit troublesome, so it could be worth looking at possibilities for auto-generating the API from backend as it now has taken form.

**Comment by nicomni** [comment]
[Maybe some useful info here](https://www.django-rest-framework.org/topics/documenting-your-api/#self-describing-apis)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kalkins** [comment]
I'm working on using drf-yasg to do this. It seems doable, but it requires some updates to the backend views to tell the API generator all the details it can't infer automatically
